// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5ld2wTEDAvi1Rspdmg6gMRMNPjF350OI',
    appId: '1:546784331733:web:7f6b783c6d0cc4a9f65f5c',
    messagingSenderId: '546784331733',
    projectId: 'tea-shop-3b821',
    authDomain: 'tea-shop-3b821.firebaseapp.com',
    storageBucket: 'tea-shop-3b821.firebasestorage.app',
    measurementId: 'G-C3LCPGL4M8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2Ce-UgWDznU-wfJnsf9PBPWOctv_mcao',
    appId: '1:546784331733:android:a26556e41ac1f0cef65f5c',
    messagingSenderId: '546784331733',
    projectId: 'tea-shop-3b821',
    storageBucket: 'tea-shop-3b821.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfIqHhmcINLFwXWAaAx3tR8sj-NEG_gYY',
    appId: '1:546784331733:ios:bfdaa181212bfc49f65f5c',
    messagingSenderId: '546784331733',
    projectId: 'tea-shop-3b821',
    storageBucket: 'tea-shop-3b821.firebasestorage.app',
    iosBundleId: 'com.example.pos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfIqHhmcINLFwXWAaAx3tR8sj-NEG_gYY',
    appId: '1:546784331733:ios:bfdaa181212bfc49f65f5c',
    messagingSenderId: '546784331733',
    projectId: 'tea-shop-3b821',
    storageBucket: 'tea-shop-3b821.firebasestorage.app',
    iosBundleId: 'com.example.pos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5ld2wTEDAvi1Rspdmg6gMRMNPjF350OI',
    appId: '1:546784331733:web:5db157b597fb2e0bf65f5c',
    messagingSenderId: '546784331733',
    projectId: 'tea-shop-3b821',
    authDomain: 'tea-shop-3b821.firebaseapp.com',
    storageBucket: 'tea-shop-3b821.firebasestorage.app',
    measurementId: 'G-FERSVZ5FVM',
  );
}
